Link of tutorial: https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

# Tensor

In [1]:
import torch

Create a tensor and set requires_grad=True to track computation with it:

In [2]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

Do a tensor operation:

In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

Do more operations on y:

In [5]:
z = y * y * 3
out = z.mean()

z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))